 const productDescriptions = {
  semanal:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  universitaria:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  docente:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  rayado:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  cuadriculado:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  punteado:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  kakeibo:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  baby:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  sanitariaClasica:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  sanitariaDeluxe:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  nihon:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  miryoku:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  tradicionales:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.',
  personalizadas:  'Lorem ipsum dolor sit amet consectetur adipisicing elit. At unde dolor voluptatum veniam iusto nostrum nesciunt tempora harum repudiandae fuga corporis maxime quam assumenda aut similique rem porro et, nulla aperiam quod possimus ullam praesentium aspernatur? Et tenetur corrupti molestiae. Voluptate quis aspernatur quos illum ipsa quaerat labore officia possimus saepe quam? Nulla, incidunt alias suscipit earum vitae qui dignissimos.'
};

export default productDescriptions;